### ISSUE TITLE
While running crisis_cnn, I am getting following error.

### ISSUE THREAD

**Issue by Rajratnpranesh** [CrisisNLP/deep-learning-for-big-crisis-data#4]
Using TensorFlow backend.
Loading data...
Traceback (most recent call last):
Nb of tweets: train: 0 test: 0 dev: 0
  File "C:/Users/RAJ RATN PRANESH/Documents/GitHub/deep-learning-for-big-crisis-data/dnn_scripts/cnn_crisis.py", line 187, in <module>
Total vocabulary size: 0
    nb_classes = np.max(y_train) + 1
Pruned vocabulary size: 80% =0
  File "C:\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 2504, in amax
Random seed 113
    initial=initial)
  File "C:\Python\Python37\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

Process finished with exit code 1

**Comment by Rajratnpranesh** [comment]
Use Python 2.7 and the required version of libraries and packages. Change the directory of the data according to yourself. Some of the syntax and command are deprecated, so install the require version of the libs or try to modify the code according to the new syntaxes.
